### ISSUE TITLE
Programming AM29F040

### ISSUE THREAD

**Issue by TnnsBeast** [vascofazza/8bit-cpu#11]
Hi there, how did you go about programming the AM29F040 flash memory? I have built the eeprom programmer but from what I can tell that is setup to program the EEPROM handling the 7 segment leds. I am unable to find a good example of how to program the AM29F040 online. Your help is greatly appreciated!

**Comment by vascofazza** [comment]
Hi, 
you can build the eeprom_programmer board and use this to program the 7 segment driver: https://github.com/vascofazza/8bit-cpu/tree/master/eeprom_programmer/multiplexed-display
Schematics: https://github.com/vascofazza/8bit-cpu/tree/master/eeprom_programmer/arduino_eeprom_programmer
Otherwise you can simply use an EEPROM programmer like the MiniPro TL866

**Comment by TnnsBeast** [comment]
Hi, I have successfully built the eeprom programmer board and programmed the 7 segment driver. I am still struggling with the AM29F040 flash chips. I have spent many hours trying to build a programmer for it, but have not been successful. Could you please tell me how you program the AM29F040 chips which are used for control logic and programming interface. Without that I am unable to get this project working, and would really appreciate your help.

**Comment by vascofazza** [comment]
@TnnsBeast I used a programmer.
You can try this one off https://github.com/warber0x/FMPUNO
Let me know!
